### ISSUE TITLE
Add example for GeoSPARQL

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j-doc#19]
See also https://github.com/eclipse/rdf4j/issues/605

I'll try to come up with an example, but where should I put it ?
(doc/programming/03-repository-api ?)

**Comment by jinjin304616** [comment]
Hi, can you email me a copy please? really want to make GeoSparql work for my application. thanks.

**Comment by jeenbroekstra** [comment]
@barthanssens Awesome! I'd suggest adding it to 05-custom-sails, or even just start a new chapter (06-geosparql). But feel free to do what is easiest for you, the important thing is to get something on paper, we can always rearrange later :)

**Comment by barthanssens** [comment]
Ok, I'll start a new chapter, since it probably won't hurt to add some basic details on geo/spatial as well.

**Comment by barthanssens** [comment]
@jinjin304616 an extremely simple example can be found in the fork (https://github.com/Fedict/rdf4j-doc/blob/issues/%2319-geosparql-example/doc/programming/06-geosparql.adoc), still work in progress though perhaps you may find it useful

**Comment by jinjin304616** [comment]
Thanks for this Bart. In your example, you add coordinates into repository using  and query them from repository:
con.add(am, GEO.AS_WKT, fac.createLiteral(toWkt(amsterdam), GEO.WKT_LITERAL));

List<BindingSet> results = Repositories.tupleQuery(repo, qry,

                                                   r -> QueryResults.asList(r));

can they be added into a model and query from the model  instead? For example:
            model.add(am, GEO.AS_WKT, factory.createLiteral(toWKT(amsterdam)), GEO.WKT_LITERAL);

List<BindingSet> results = Model.tupleQuery(model, qry,

                                                   r -> QueryResults.asList(r));



How can I make it work?

**Comment by jeenbroekstra** [comment]
@jinjin304616 what you want is not possible. In RDF4J, a Model can not be queried using SPARQL. I suggest you have a look at this tutorial: http://docs.rdf4j.org/rdf-tutorial  .

**Comment by jinjin304616** [comment]
Thanks. I’m manage to read an owl file into a repository and can do some SPARQL queries successfully now. But I still can’t make the GeoSparql function working properly, See codes below:

    public static void main(String[] args) throws IOException  {
        File dataDir = new File("C:/RDF4J/");
        String indexes = "spoc, posc, cosp";
        Repository repo = new SailRepository(new NativeStore(dataDir, indexes));
        repo.initialize();
        File file = new File("C:/RDF4J/POI-case-study.owl");
        String baseURI = "http://www.semanticweb.org/CRCSI/POI-case-study#";
        try {
            RepositoryConnection conn = repo.getConnection();

            try {
                conn.add(file, baseURI, RDFFormat.RDFXML);
                String queryString =
                "PREFIX POI-case-study:<http://www.semanticweb.org/CRCSI/POI-case-study#>\n" +
                "PREFIX geo:<http://www.opengis.net/ont/geosparql#>\n" +
                "PREFIX geof: <http://www.opengis.net/def/function/geosparql/>" +
                "PREFIX geosf: <http://www.opengis.net/ont/sf#>" +

                "SELECT ?poi ?wkt1 ?name ?pol ?wkt2 \n" +
                "WHERE {\n" +
                " ?poi a POI-case-study:PointsOfInterest; POI-case-study:name ?name; geo:hasGeometry ?g1. \n" +
                "?g1 a geosf:Point; geo:asWKT ?wkt1. \n" +
                " ?pol a POI-case-study:Footprints; geo:hasGeometry ?g2. \n" +
                "?g2 a geosf:Polygon; geo:asWKT ?wkt2. \n" +
                " BIND(geof:within(?g1 ?g2)) \n" +   // get nothing if I add in this line, otherwise I can get many points and polygons fulfil the query
                "}" +
                "ORDER By ASC(?name)";

                TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, queryString);
                TupleQueryResult result = tupleQuery.evaluate();
                try {
                    while (result.hasNext()){
                        BindingSet bindingSet = result.next();
                        System.out.println(bindingSet.getValue("poi").stringValue() + bindingSet.getValue("wkt1").stringValue() + bindingSet.getValue("name").stringValue()
                                + bindingSet.getValue("pol").stringValue() + bindingSet.getValue("wkt2").stringValue());
                    }

                } finally {result.close();}

            }
            finally {conn.close();}


            }catch (RDF4JException e){}


Result as follow:

Scanning for projects...

------------------------------------------------------------------------
Building owltutorial 1.1
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ owltutorial ---
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 2.264s
Finished at: Tue Jan 31 14:11:55 AWST 2017
Final Memory: 7M/245M
------------------------------------------------------------------------

**Comment by barthanssens** [comment]
@jinjin304616 it seems that your query is not well-formed (e.g. take care that there is a whitespace or newline at the end of each PREFIX line
And if you use BIND, you have to bind it to some variable (BIND... AS ?somevar)

Could you put your java project, and if possible also your owl file, on github or something ? That's going to be easier than using comments on this ticket.

**Comment by jinjin304616** [comment]
@barthanssens Thanks for your reply. I tried to put the two files on github, but failed to do it cause I'm not quite familiar with it. Could you please give me an email address? I can send the java code and ontology to you directly.

**Comment by barthanssens** [comment]
@jinjin304616  you can send the files to bhfedict [at] gmail.com
