### ISSUE TITLE
SAIL Main classes not working on docs

### ISSUE THREAD

**Issue by jomach** [eclipse/rdf4j-doc#37]
Hi guys, this is not working : http://docs.rdf4j.org/sail/#figure-sail-main

**Comment by jeenbroekstra** [comment]
Thanks for reporting this @jomach. Looks like I forgot to install GraphViz when migrating the site to the Eclipse server. I'll try and look into it tonight or this weekend.

**Comment by jeenbroekstra** [comment]
Fixed.
