### ISSUE TITLE
Add default-graph-uri and named-graph-uri to documentation of SPARQL  endpoint

### ISSUE THREAD

**Issue by peterjohnlawrence** [eclipse/rdf4j-doc#38]
The SPARQL standard supports default-graph-uri and named-graph-uri as parameters of the GET/POST, yet RDF4J does not document them here: http://docs.rdf4j.org/rest-api/ repository queries.

**Comment by jeenbroekstra** [comment]
This issue was moved to eclipse/rdf4j#1119
