### ISSUE TITLE
Add text searching manual

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j-doc#49]
There is no manual how to create SPARQL text search query for both:
- [ ] LuceneSearch
- [ ] LuceneSpinSail

**Comment by barthanssens** [comment]
Do you mean something like http://docs.rdf4j.org/programming/#_full_text_search ? (actually more like an example, not a real manual)

**Comment by jeenbroekstra** [comment]
This issue was moved to eclipse/rdf4j#1120
