### ISSUE TITLE
Automated transaction handling example

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j-doc#6]
I think there is a small error in the "Automated transaction handling" try-with-resources example (03-repository-api.adoc).

> try (RepositoryConnection conn = myRepository.getConnection()) {
>    conn.begin();
> ...
>    conn.commit();
> } catch (RepositoryException e) {
>    conn.rollback();
> }

The `conn` object will not be available in the catch block, so it won't compile (and even if it was, the Autocloseable will close the resource before executing the catch block)

(of course the Repositories utility class is still easier to use)

**Comment by jeenbroekstra** [comment]
Good point Bart, thank you. Will fix ASAP.
